site_name: Mesh Sorocaba
site_url: https://www.meshsorocaba.org
repo_url: https://github.com/MeshSorocaba/meshsorocaba.github.io/
edit_uri: edit/main/docs/

theme:
  name: material
  locale: pt
  icon:
    logo: fontawesome/solid/industry
  favicon: img/favicon.png
  features:
      - navigation.tabs
      - navigation.tabs.sticky
      - toc.integrate
      - content.action.view
      - content.action.edit
  palette:
      # The custom Meshtastic theme uses `slate` as a base
      scheme: slate

nav:
  - Início: index.md
  - Guia Rápido: guia-rapido.md
  - Configuração Regional: configuracao.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list

extra_css:
  - styles/extra.css

plugins:
  - search
  - social:
      cards_layout: default
      cards_layout_options:
        background_color: "#2C2D3C"
        color: "#67EA94"
  - git-revision-date-localized:
      enable_creation_date: false
      type: date
  - git-committers:
      repository: MeshSorocaba/meshsorocaba.github.io
      branch: main



extra:
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/meshsorocaba
    - icon: fontawesome/brands/github
      link: https://github.com/MeshSorocaba