site_name: Mesh Sorocaba
site_url: https://www.meshsorocaba.org
repo_url: https://github.com/MeshSorocaba/meshsorocaba.github.io/
edit_uri: edit/main/docs/

theme:
  name: material
  locale: pt_br
  icon:
    logo: fontawesome/solid/industry
  favicon: img/favicon.png
  features:
      - navigation.tabs
      - navigation.tabs.sticky
      - toc.integrate
      - content.action.view
      - content.action.edit
  palette:
      # The custom Meshtastic theme uses `slate` as a base
      scheme: slate
      primary: indigo
      accent: cyan

nav:
  - Início: index.md
  - Guia Rápido: guia-rapido.md
  - MeshCore:
    - Índice: meshcore/index.md
    - Configuração Recomendada: meshcore/configuracao.md
    - Nomenclatura para Repetidoras: meshcore/nomes-repetidoras.md
  - Meshtastic:
    - Índice: meshtastic/index.md
    - Configuração Recomendada: meshtastic/configuracao.md
  - Blog:
    - blog/index.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.blocks.caption

extra_css:
  - styles/extra.css

extra_javascript:
  - js/repeater-name-generator.js


plugins:
  - search
  - blog:
      authors_file: "{blog}/.authors.yml"
  - social:
      cards_layout: default
      cards_layout_options:
        background_color: "#2C2D3C"
        color: "#70a2e4"
  - git-revision-date-localized:
      enable_creation_date: false
      type: date
  - git-committers:
      repository: MeshSorocaba/meshsorocaba.github.io
      branch: main



extra:
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/meshsorocaba
    - icon: fontawesome/brands/github
      link: https://github.com/MeshSorocaba
